name: Main Branch Automated Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Create .env file
        if: ${{ always() }}
        run: |
          touch .env
          echo BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }} >> .env
          echo BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}  >> .env

      - name: Install dependencies
        if: ${{ always() }}
        run: npm install

      - name: Execute tests
        if: ${{ always() }}
        run: |
          npm run wdio

    # - name: Upload test report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test-report
    #     path: reports/

  # You can add more steps for deployment or other actions as needed.
